theme = "hugo-bearblog"

baseURL = "https://fsis.site/"
languageCode = "en-US"
title = "fsis.site ğŸ´"
author = "FSi"
copyright = "Copyright Â© 2020, FSi"

enableRobotsTXT = true

[params]
  description = "fsi's personal site and blog"
  favicon = "images/logo.png"
  title = "fsis.site ğŸ´"
  images = ["images/logo.png"]